# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-EmoRec' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-EmoRec

  pod "Macaw", "0.9.7"

  pod 'Firebase/Analytics'
end
