# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'project-Emotion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for project-Emotion
  pod 'Firebase/Analytics'
  pod "Macaw", "0.9.7"
  pod "WaveAnimationView", "1.0.2"
  pod "TweenKit", "1.0.3"

end
